### ISSUE TITLE
Data generated from AzureHound cannot be imported in BloodHound

### ISSUE THREAD

**Issue by JoeHO888** [BloodHoundAD/AzureHound#1]
I generate the data with below command
`azurehound.exe -r "<<refresh-token>>" list --tenant "<<tenant>>" -o output.json`

The export data is something as below
`{
	"data": [
		{"kind":"AZTenant","data":{...},
                {"kind":"AZManagementGroup",","data":{...},
                ...
        ],
        "meta": {"type":"azure","version":5,"count":xxx}
}`

However, Bloodhound cannot recognize the data format.
![image](https://user-images.githubusercontent.com/29224653/183226945-c4216411-ea18-441a-800b-caa5dfc6aa31.png)

Azurehound version: v1.1.2
Bloodhound version: v4.2.0

**Comment by johnjohnsp1** [comment]
hi,
how did you solved ? i have the same problem, thanks

**Comment by JoeHO888** [comment]
I was using old version bloodhound when I created this issue

Using the latest version of azurehound and bloodhound should fix.

**Comment by johnjohnsp1** [comment]
may i ask you how to get the refresh token ? i miss that part, if you can of course thanks
