### ISSUE TITLE
AzureHound Zip File OutPut Invalid

### ISSUE THREAD

**Issue by arishwani** [BloodHoundAD/AzureHound#16]
Hi, 
I ma having issues with AzureHound zip file. After I generate the zip file through Azurehound powershell script, I tried importing to Bloodhound UI but it says it "Invalid file type" in Bloodhound. Is this issue related to anything? How can be fixed? 

Thank you 
Ari

**Comment by ddlees** [comment]
@arishwani We no longer support the [AzureHound PowerShell script](https://github.com/BloodHoundAD/Legacy-AzureHound.ps1). I recommend downloading the latest version of the new AzureHound client from our [releases page](https://github.com/BloodHoundAD/AzureHound/releases). If you have any questions on how to use the new client I recommend reaching out to us via [BloodHound Gang on Slack](https://bloodhoundgang.herokuapp.com/).

**Comment by arishwani** [comment]
@ddlees Thank you for your response. So with AzureHound client I don't see an option to ouput the result into Zip file so I could later import it to Bloodhound. Can you please provide the command for outputting the result of AzureHound client into zip file?

**Comment by ddlees** [comment]
@arishwani You shouldn't need to convert the output to a zip format for recent versions of BloodHound but if you still wish to do you can use 7zip (or a compression tool of your choice) to convert the output json into a zip file.

E.g.

``` sh
azurehound list -o mytenant.json
7z a -tzip -mx9 mytenant.zip mytenant.json
```
