### ISSUE TITLE
Missing app role assignments

### ISSUE THREAD

**Issue by hugo-syn** [BloodHoundAD/AzureHound#2]
Hello, 

It would be great to retrieve the different app role assignments to find new attack paths like the ones described in this article: https://posts.specterops.io/azure-privilege-escalation-via-azure-api-permissions-abuse-74aee1006f48.

Is this something that is on the roadmap ? Otherwise, I could work on a PR.

Thank you :)

**Comment by ddlees** [comment]
@hugo-syn Yes, getting the app role assignments is on our roadmap, however, you are more than welcome to submit a PR.
