### ISSUE TITLE
Azure Application Object ID seems wrong

### ISSUE THREAD

**Issue by 0xbad53c** [BloodHoundAD/AzureHound#24]
Hi folks,

Thank you for creating this awesome ingestor. I've been diving into Azure recently and this helped me a lot to understand some of the dangerous relationships that can occur. However, I have some difficulties understanding certain application relationships.

In my test tenant I set up an application AAD-Management-App with dangerous permissions. I am now trying to discover an attack path to it. The scenario is essentially to phish the Rudolph Rednose user (HelpDesk Admin) and then use his credentials to reset Mary Mistletoe's password. She is the owner of the aforementioned application with dangerous permissions.

However, I appear to be having 2 entries for the AAD-Management-App in my AzureHound data. I think this might be because of a bug in AzureHound. I found a mismatch in object id. Consider the following information (according to Azure portal and RoadTools:
Application:
Display name	AAD-Management-App
ObjectId	9b344f88-c707-47ef-af08-2eba1eb3951c
Application ID	706dc2e7-b3b3-4208-b5e7-5934f4a4575f

Service Principal:
Display name	AAD-Management-App
ObjectId	57892ae4-b45e-48fa-b3fd-a733d740297d
AppId	706dc2e7-b3b3-4208-b5e7-5934f4a4575f

In the BloodHound UI, I can find and inspect the application. Please note how the Object ID and Application ID are the same. Sadly, I cannot map owners to this BloodHound UI object:  
<img width="1166" alt="Screenshot 2022-12-13 at 22 55 06" src="https://user-images.githubusercontent.com/74974697/207452676-033c61c9-ae47-4d59-86db-96abb6916c4f.png">

This is different when I search purely on the object ID (9b344f88-c707-47ef-af08-2eba1eb3951c). I can correctly map the owner and I can see that the service principal id is the same, but I cannot click the service principal to show the relationship. The UI also does not show the application name or other properties:
<img width="790" alt="Screenshot 2022-12-13 at 22 59 52" src="https://user-images.githubusercontent.com/74974697/207453435-97bd3abb-4d13-4578-beef-52425ac90109.png">

It seems to me that the object id in the first image should have been 9b344f88-c707-47ef-af08-2eba1eb3951c to map all properties correctly to the same object. What do you think?

**Comment by andyrobbins** [comment]
Hi @0xbad53c, thanks for opening this issue

I can confirm this is not the intended behavior and have replicated what you're seeing here with the mismatch between an "Owned" app and an app associated with a service principal. I'm going to work on figuring out the root cause so I can propose a fix ASAP.

**Comment by andyrobbins** [comment]
Hi @0xbad53c 

I believe we identified the root cause here and are working on a fix now. We should be able to test the fix internally by tomorrow
