### ISSUE TITLE
Data collection on ConnectAz connected Powershell

### ISSUE THREAD

**Issue by floyd-fuh** [BloodHoundAD/AzureHound#34]
Hi there,

Thanks a lot for creating this tool.

I'm currently unable to run AzureHound as there are heavy conditional access controls in place for the environment under test. What I've tried:

1. Using AzureHound from a third-party computer with "-u -p -t" fails because of conditional access
2. Using the "Powershell+Browser login" as described on [dealing with multi-factor auth and conditional access policies ](https://bloodhound.readthedocs.io/en/latest/data-collection/azurehound.html#dealing-with-multi-factor-auth-and-conditional-access-policies) fails with Azure preventing me to do a login with the error: "You cannot access this right now. Your sign-in was successful, but does not meet the criteria to access this resource. For example, you might be signing in from a browser, app or location that is restricted by your admin." which sounds like conditional access problems again.
3. I've connected with ConnectAz and extracted the access token with:
```
$currentAzureContext = Get-AzContext
$azureRmProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile;
$profileClient = New-Object Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient($azureRmProfile);
$profileClient.AcquireAccessToken("XXX-TENANT_ID-XXX").AccessToken;
```
But it looks like AzureHound's `-r` option is expecting a refresh token rather than an access token and therefore fails with `failed to create new Azure client: map[correlation_id:XXX error:invalid_grant error_codes`

4. I've also passed the JTW tokens that can be acquired with Powershell's `Save-AzContext` to AzureHound's `-r` but no luck there either.
5. I've obfuscated the AzureHound source code and built it so it doesn't get detected by the AV. It runs on the target computer now, and I am able to do `ConnectAz` to connect to Azure. But there is no option in AzureHound to use this connection AFAIK.
6. I've asked for AAD administrative access (to create a new application ID etc.), but this is really last resort as this is possible on this engagement but is usually not feasible.

My questions:

1. Is it possible to tell AzureHound to "use the Azure session from this Powershell" when ConnectAz was run?
2. Is it possible to use an access_token rather than a refresh_token? I know how JWT works, if Azure is working like most JWT setups, it should be sufficient to use the access_token as long as it is still valid (only on expiry we need to fetch a new access_token by using the refresh_token, right?)
3. Any other hints on what might be the easiest way to run AzureHound?

**Comment by andyrobbins** [comment]
Hi @floyd-fuh 

You can provide the JWT to AzureHound by using the `-j` switch. For example:

```
MacBook-Pro-7:AzureHound andyrobbins$ ./azurehound list az-ad --tenant "specterdev.onmicrosoft.com" -j "eyJ0eXAi<...>rNQ" -o az-ad.json
AzureHound v0.0.0
Created by the BloodHound Enterprise team - https://bloodhoundenterprise.io

2023-03-13T08:03:40-07:00 INF collecting azure ad objects...
2023-03-13T08:03:40-07:00 ERR unable to continue processing tenants error="invalid audience"
2023-03-13T08:03:42-07:00 INF finished listing all devices count=11
2023-03-13T08:03:42-07:00 INF finished listing all groups count=30
2023-03-13T08:03:42-07:00 INF finished listing all users count=175
2023-03-13T08:03:45-07:00 INF finished listing all device owners
2023-03-13T08:03:46-07:00 INF finished listing all group owners
2023-03-13T08:03:49-07:00 INF finished listing all roles count=105
2023-03-13T08:03:54-07:00 INF finished listing all role assignments
2023-03-13T08:04:05-07:00 INF finished listing members for all groups
<etc>
```

Please note that your token audience must match the data source you are collecting from. If you are collecting from AzureAD, your token audience must match `https://graph.microsoft.com`. If you are collecting from AzureRM, your token audience must match `https://management.azure.com/`.

**Comment by floyd-fuh** [comment]
I'm aksing myself how I could miss `-j`, thanks a lot for the pointer. And I've even found a refresh_token by now, so `-r` works, too. Looking a lot closer into the output of `Save-AzContext` was the key. Cheers!
