### ISSUE TITLE
 ERR unable to continue processing members for this group error="attempting to handle 429 but unable to parse retry-after header

### ISSUE THREAD

**Issue by ahmedsherif** [BloodHoundAD/AzureHound#35]
I'm running AzureHound collector on large AzureAD (~300,000 users). However, after sometime I'm receiving the following error: 

`ERR unable to continue processing owners for this app error="attempting to handle 429 but unable to parse retry-after header: strconv.ParseInt: parsing \"\": invalid syntax" appId=REDACTED`

it keeps giving this error until it shutdown. 

the command used is just for collecting all the tenants objects: 

`azurehound -r 'token' list --tenant 'company.com' -o output.json`

**Comment by StephenHinck** [comment]
Can you confirm whether this still occurs? We've made a significant number of changes since this was opened and haven't seen it ourselves. Feel free to re-open if so!
