### ISSUE TITLE
Convert-to-json error: OutOfMemoryException

### ISSUE THREAD

**Issue by yellow-starburst** [BloodHoundAD/AzureHound#5]
After  `Writing output for pwresetrights` I receive the following error: 
`ConvertTo-Json : Exception of type 'System.OutOfMemoryException' was thrown.`

I am running on a system that has an excessive amount of ram - over 20 gb+

**Comment by DPeltier** [comment]
Hi, same issue on my side. I tried few things without finding a solution.

**Comment by smy1es** [comment]
I had the same issue as well with a machine with 48GB memory. I have created pull request #9 which reduces memory consumption when running with large domains considerably by doing the output in chunks.

**Comment by yellow-starburst** [comment]
Would be glad to close this issue once pull request has been merged.

**Comment by yellow-starburst** [comment]
Thanks @smy1es!!
