### ISSUE TITLE
Null in DisplayName causing import issue

### ISSUE THREAD

**Issue by mubix** [BloodHoundAD/AzureHound#6]
The output from AzureHound resulted in a `null` in one of the DisplayName field for one the AZgroups.json objects. This made BloodHound fail on import. I believe this could be fixed on either end, but it looks this others are having the same issue and have reported it on the BloodHound side: 
- https://github.com/BloodHoundAD/BloodHound/issues/395
- https://github.com/BloodHoundAD/BloodHound/issues/401
- https://github.com/BloodHoundAD/BloodHound/issues/402

![NullName](https://user-images.githubusercontent.com/679319/101048348-8b8f1d00-3550-11eb-9185-13804f8b4e56.png)

**Comment by ViperGDC** [comment]
@mubix was running into the same issue, this was fixed in the latest AzureHound release.
