### ISSUE TITLE
Killed process

### ISSUE THREAD

**Issue by codeitch** [BloodHoundAD/AzureHound#6]
It seems that in a case of bigger items (such as users count being 200k), the azurehound gets killed. Before it gets killed, it throws the following error:

_ERR unable to continue processing owners for this device error="Get \"https://graph.microsoft.com/v1.0/devices[...]: read: connection reset by peer"_  

Is there any suggestion for a possible workaround of enumerating these larger items?

**Comment by ddlees** [comment]
### Acceptance Criteria

- Introduce new subcommand `azurehound list device-role-assignments` similar to the implementation of `azurehound list virtual-machine-role-assignments`
- Refactor all `azurehound list virtual-machine-*` subcommands to use the piped output of virtual machine role assignments.

**Comment by ddlees** [comment]
@codeitch Apologies; this issue got a little stale. Can you try what's in the [Rolling Release](https://github.com/BloodHoundAD/AzureHound/releases/tag/rolling) to see if you're still experiencing the same issue with large datasets? There have been a number of changes that should improve your prior experience.

**Comment by StephenHinck** [comment]
Closing as no additional information has been provided. Please feel free to re-open if you have any additional information to help us troubleshoot.
