### ISSUE TITLE
On-Prem AD Group Role Assignments not shown

### ISSUE THREAD

**Issue by fl0mb** [BloodHoundAD/AzureHound#8]
In a recent pentest several Azure roles were found to be assigned to a group synced from on-prem AD. The pentest is purely focused on Azure, so no additional Sharphound scan is possible.

When analyzing the data, Bloodhound did not show any roles for this particular group. However all roles assigned to cloud based groups show up correctly.

Not sure if this is an issue or if I just do not know how to properly use AzureHound.

**Comment by ddlees** [comment]
@fl0mb BloodHound treats the on-prem Group and the cloud sync'd AZGroup as two distinct entity types. If you're only running AzureHound and the local Group was successfully sync'd to AzureAD, you should see an AZGroup that represents the local Group and only the AzureAD roles assigned to that group.

We are still trying to work out how to best model the hybrid case. There are certain things that happen during the sync between on-prem AD and AzureAD (and vice versa) that we don't fully understand for each of the methods organizations use to keep their environments synchronized.

I personally do not know how on-prem role assignments get sync'd or if they do at all but I do know @andyrobbins has some thoughts/opinions on this subject. I would recommend joining the [BloodHound Gang Slack](https://bloodhoundgang.herokuapp.com/), if you haven't done so already, and pick brain of the collective "think tank" for more information.
